sudo: false
language: node_js
node_js:
  - '8'
  - '9'
  - '10'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sequelizer_test_one; CREATE DATABASE IF NOT EXISTS sequelizer_test_two;'
